### ISSUE TITLE
Connect Webdriver.io to BrowserStack Local on Bamboo without this plugin?

### ISSUE THREAD

**Issue by snoblenet** [browserstack/browserstack-bamboo-integration#5]
Hi there,

Is it possible to connect Webdriver.io to BrowserStack Local on Bamboo without this plugin?

I'm not sure how long it will take to get the use of this plug-in approved by the organisation.

I've got everything working just fine locally, but on Bamboo, the error is:

`'ERROR: [browserstack.local] is set to true but local testing through BrowserStack is not connected`

**Comment by ckzgraphics** [comment]
Yes. It is indeed possible to use BrowserStack Local without a Bamboo plugin. You may run a shell script to execute the [BrowserStackLocal binary](https://www.browserstack.com/local-testing/automate#enable-local-testing-automate) before your tests start.

Possible reasons the error- [browserstack.local] is set to true but local testing through BrowserStack is not connected
- BrowserStackLocal binary is not running
- Your test script and BrowserStackLocal binary connection do not use the same username and access key
- If you are using Local Identifier, then your test script and BrowserStackLocal binary connection do not use the same local identifier
