### ISSUE TITLE
Browserstack Local been start for all available job in Bamboo

### ISSUE THREAD

**Issue by ezwanharun** [browserstack/browserstack-bamboo-integration#8]
Noticed that this plugin has been started for all available bamboo job which caused memory consumption is too high when all job been run parallel due to auto deploy/build. Is there any configuration that need to be configure so that only specific related job will only start this plugin to connect with Browserstack Local?

**Comment by pulkitsharma07** [comment]
Closing as duplicate of https://github.com/browserstack/browserstack-bamboo-integration/issues/7
